-- VR Classroom Studio V15 — invitations, activity audit and realtime publication
-- Requires schema_v13.sql and schema_v14.sql.
-- Apply only to a dedicated VR Classroom Studio Supabase project.

create table if not exists public.xr_workspace_invites (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.xr_workspaces(id) on delete cascade,
  invited_email text not null,
  role text not null check (role in ('admin','instructor','reviewer')),
  invited_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (expires_at > created_at)
);

create table if not exists public.xr_activity_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.xr_workspaces(id) on delete cascade,
  project_id uuid references public.xr_projects(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 2 and 120),
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists xr_workspace_invites_workspace_idx on public.xr_workspace_invites(workspace_id, created_at desc);
create index if not exists xr_workspace_invites_email_idx on public.xr_workspace_invites(lower(invited_email), expires_at);
create index if not exists xr_activity_events_workspace_idx on public.xr_activity_events(workspace_id, created_at desc);
create index if not exists xr_activity_events_project_idx on public.xr_activity_events(project_id, created_at desc);

alter table public.xr_workspace_invites enable row level security;
alter table public.xr_activity_events enable row level security;

drop policy if exists "xr_invites_admin_select" on public.xr_workspace_invites;
create policy "xr_invites_admin_select" on public.xr_workspace_invites
for select to authenticated
using (public.xr_is_workspace_admin(workspace_id));

drop policy if exists "xr_invites_admin_insert" on public.xr_workspace_invites;
create policy "xr_invites_admin_insert" on public.xr_workspace_invites
for insert to authenticated
with check (
  invited_by = (select auth.uid())
  and public.xr_is_workspace_admin(workspace_id)
);

drop policy if exists "xr_invites_admin_update" on public.xr_workspace_invites;
create policy "xr_invites_admin_update" on public.xr_workspace_invites
for update to authenticated
using (public.xr_is_workspace_admin(workspace_id))
with check (public.xr_is_workspace_admin(workspace_id));

drop policy if exists "xr_invites_admin_delete" on public.xr_workspace_invites;
create policy "xr_invites_admin_delete" on public.xr_workspace_invites
for delete to authenticated
using (public.xr_is_workspace_admin(workspace_id));

create or replace function public.xr_my_pending_invites()
returns table (
  invite_id uuid,
  workspace_id uuid,
  workspace_name text,
  role text,
  expires_at timestamptz
)
language sql stable security definer
set search_path = public
as $$
  select i.id, i.workspace_id, w.name, i.role, i.expires_at
  from public.xr_workspace_invites i
  join public.xr_workspaces w on w.id = i.workspace_id
  where i.accepted_at is null
    and i.expires_at > now()
    and lower(i.invited_email) = lower(coalesce((select auth.jwt()->>'email'), ''))
$$;

create or replace function public.xr_claim_workspace_invite(target_invite uuid)
returns uuid
language plpgsql security definer
set search_path = public
as $$
declare
  inv public.xr_workspace_invites%rowtype;
  caller uuid := (select auth.uid());
  caller_email text := lower(coalesce((select auth.jwt()->>'email'), ''));
begin
  if caller is null then
    raise exception 'authentication required';
  end if;

  select * into inv
  from public.xr_workspace_invites
  where id = target_invite
  for update;

  if not found then
    raise exception 'invite not found';
  end if;

  if inv.accepted_at is not null then
    raise exception 'invite already accepted';
  end if;

  if inv.expires_at <= now() then
    raise exception 'invite expired';
  end if;

  if lower(inv.invited_email) <> caller_email then
    raise exception 'invite email does not match authenticated user';
  end if;

  insert into public.xr_workspace_members(workspace_id,user_id,role)
  values(inv.workspace_id,caller,inv.role)
  on conflict (workspace_id,user_id)
  do update set role = excluded.role;

  update public.xr_workspace_invites
  set accepted_at = now(), accepted_by = caller
  where id = inv.id;

  return inv.workspace_id;
end;
$$;

revoke all on function public.xr_my_pending_invites() from public;
revoke all on function public.xr_claim_workspace_invite(uuid) from public;
grant execute on function public.xr_my_pending_invites() to authenticated;
grant execute on function public.xr_claim_workspace_invite(uuid) to authenticated;

drop policy if exists "xr_activity_select" on public.xr_activity_events;
create policy "xr_activity_select" on public.xr_activity_events
for select to authenticated
using (public.xr_is_workspace_member(workspace_id));

drop policy if exists "xr_activity_insert" on public.xr_activity_events;
create policy "xr_activity_insert" on public.xr_activity_events
for insert to authenticated
with check (
  actor_id = (select auth.uid())
  and public.xr_is_workspace_member(workspace_id)
  and (
    project_id is null
    or public.xr_project_workspace(project_id) = workspace_id
  )
);

grant select, insert, update, delete on public.xr_workspace_invites to authenticated;
grant select, insert on public.xr_activity_events to authenticated;

-- Protect immutable invitation identity fields.
create or replace function public.xr_protect_invite_identity()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.workspace_id is distinct from old.workspace_id
     or new.invited_email is distinct from old.invited_email
     or new.invited_by is distinct from old.invited_by then
    raise exception 'invite identity fields are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists xr_workspace_invites_protect_identity on public.xr_workspace_invites;
create trigger xr_workspace_invites_protect_identity
before update on public.xr_workspace_invites
for each row execute function public.xr_protect_invite_identity();

-- Realtime publication for collaboration data. Presence/broadcast channels do not require table publication,
-- but these rows can be subscribed to for live review/task/approval refresh.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'xr_review_comments'
  ) then
    alter publication supabase_realtime add table public.xr_review_comments;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'xr_review_tasks'
  ) then
    alter publication supabase_realtime add table public.xr_review_tasks;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'xr_project_approvals'
  ) then
    alter publication supabase_realtime add table public.xr_project_approvals;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'xr_project_locks'
  ) then
    alter publication supabase_realtime add table public.xr_project_locks;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'xr_media_assets'
  ) then
    alter publication supabase_realtime add table public.xr_media_assets;
  end if;
end $$;
