-- VR Classroom Studio V21 — institutional release management
-- Requires schema_v13.sql through schema_v20.sql.
-- Apply only to a dedicated VR Classroom Studio Supabase project.

create table if not exists public.xr_releases (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.xr_projects(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  version text not null check (version ~ '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$'),
  name text not null check (char_length(name) between 1 and 240),
  status text not null default 'draft' check (status in ('draft','qa','approved','published','retired')),
  project_fingerprint text not null check (project_fingerprint ~ '^[0-9a-f]{64}$'),
  release_candidate_id uuid not null references public.xr_release_candidates(id) on delete restrict,
  summary jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, version)
);

create unique index if not exists xr_releases_one_published_per_project
  on public.xr_releases(project_id)
  where status = 'published';

create index if not exists xr_releases_project_idx
  on public.xr_releases(project_id, created_at desc);

create table if not exists public.xr_release_events (
  id bigint generated by default as identity primary key,
  release_id uuid not null references public.xr_releases(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 2 and 120),
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists xr_release_events_release_idx
  on public.xr_release_events(release_id, created_at desc);

alter table public.xr_releases enable row level security;
alter table public.xr_release_events enable row level security;

drop policy if exists "xr_releases_select" on public.xr_releases;
create policy "xr_releases_select" on public.xr_releases
for select to authenticated
using (public.xr_is_workspace_member(public.xr_project_workspace(project_id)));

drop policy if exists "xr_releases_insert" on public.xr_releases;
create policy "xr_releases_insert" on public.xr_releases
for insert to authenticated
with check (
  created_by = (select auth.uid())
  and status = 'draft'
  and public.xr_can_write_workspace(public.xr_project_workspace(project_id))
  and exists (
    select 1 from public.xr_release_candidates rc
    left join public.xr_test_runs tr on tr.id = rc.test_run_id
    where rc.id = release_candidate_id
      and rc.project_id = project_id
      and coalesce(tr.passed,false) = true
  )
);

drop policy if exists "xr_release_events_select" on public.xr_release_events;
create policy "xr_release_events_select" on public.xr_release_events
for select to authenticated
using (
  exists (
    select 1 from public.xr_releases r
    where r.id = xr_release_events.release_id
      and public.xr_is_workspace_member(public.xr_project_workspace(r.project_id))
  )
);

grant select, insert on public.xr_releases to authenticated;
grant select on public.xr_release_events to authenticated;

create or replace function public.xr_release_status_rank(s text)
returns integer
language sql immutable
set search_path = public
as $$
  select case s
    when 'draft' then 0
    when 'qa' then 1
    when 'approved' then 2
    when 'published' then 3
    when 'retired' then 4
    else -1
  end
$$;

create or replace function public.xr_transition_release(target_release uuid, target_status text)
returns public.xr_releases
language plpgsql
security definer
set search_path = public
as $$
declare
  rel public.xr_releases%rowtype;
  ws uuid;
  caller uuid := (select auth.uid());
  can_write boolean;
  can_admin boolean;
  can_approve boolean;
begin
  if caller is null then
    raise exception 'authentication required';
  end if;

  select * into rel from public.xr_releases where id = target_release for update;
  if not found then
    raise exception 'release not found';
  end if;

  ws := public.xr_project_workspace(rel.project_id);
  can_write := public.xr_can_write_workspace(ws);
  can_admin := public.xr_is_workspace_admin(ws);
  can_approve := public.xr_can_approve_project(rel.project_id);

  if public.xr_release_status_rank(target_status) <> public.xr_release_status_rank(rel.status) + 1 then
    raise exception 'release transition must be sequential';
  end if;

  if target_status = 'qa' then
    if not can_write then
      raise exception 'workspace write permission required';
    end if;
    if not exists (
      select 1
      from public.xr_release_candidates rc
      join public.xr_test_runs tr on tr.id = rc.test_run_id
      where rc.id = rel.release_candidate_id
        and rc.project_id = rel.project_id
        and tr.passed = true
    ) then
      raise exception 'passing V20 test evidence is required before QA';
    end if;
  elsif target_status = 'approved' then
    if not can_approve then
      raise exception 'approval permission required';
    end if;
    if (
      select count(distinct gate)
      from public.xr_project_approvals a
      where a.project_id = rel.project_id
        and a.gate in ('instructional','accessibility','technical','final')
    ) < 4 then
      raise exception 'all four governance approvals are required';
    end if;
  elsif target_status = 'published' then
    if not can_admin then
      raise exception 'workspace admin permission required';
    end if;
    if not exists (
      select 1
      from public.xr_blackboard_validations v
      where v.project_id = rel.project_id
        and v.release_candidate_id = rel.release_candidate_id
        and v.passed = true
    ) then
      raise exception 'passing Blackboard validation for the same Release Candidate is required';
    end if;
  elsif target_status = 'retired' and not can_admin then
    raise exception 'workspace admin permission required';
  end if;

  if target_status = 'published' then
    update public.xr_releases
      set status='retired', updated_at=now()
    where project_id=rel.project_id
      and status='published'
      and id<>rel.id;
  end if;

  update public.xr_releases
    set status=target_status, updated_at=now()
  where id=rel.id
  returning * into rel;

  insert into public.xr_release_events(release_id, actor_id, event_type, event_data)
  values(rel.id, caller, 'status_transition', jsonb_build_object('to', target_status));

  return rel;
end;
$$;

revoke all on function public.xr_release_status_rank(text) from public;
revoke all on function public.xr_transition_release(uuid,text) from public;
grant execute on function public.xr_release_status_rank(text) to authenticated;
grant execute on function public.xr_transition_release(uuid,text) to authenticated;

create or replace function public.xr_protect_release_identity()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.project_id is distinct from old.project_id
     or new.created_by is distinct from old.created_by
     or new.version is distinct from old.version
     or new.project_fingerprint is distinct from old.project_fingerprint
     or new.release_candidate_id is distinct from old.release_candidate_id then
    raise exception 'release identity fields are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists xr_releases_protect_identity on public.xr_releases;
create trigger xr_releases_protect_identity
before update on public.xr_releases
for each row execute function public.xr_protect_release_identity();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='xr_releases'
  ) then
    alter publication supabase_realtime add table public.xr_releases;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='xr_release_events'
  ) then
    alter publication supabase_realtime add table public.xr_release_events;
  end if;
end $$;
